services:
  urlshortener.api:
    image: ${DOCKER_REGISTRY-}urlshortenerapi
    build:
      context: .
      dockerfile: URLShortener/Dockerfile
    depends_on:
      - urlshortener.db
      - urlshortener.redis

  urlshortener.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: URLShortener.Db

  urlshortener.redis:
    image: redis:latest
    container_name: URLShortener.Cache